/**
 * A positive integer N is given. The goal is to construct the shortest possible sequence
 * of integers ending with N, using the following rules:
 * 
 *  - the first element of the sequence is 1; more specifically A[0] = 1,
 *  - each of the following elements is generated by multiplying the previous
 *    element by 2 or increasing it by 1; more precisely: A[i] = A[i-1]*2 or
 *    A[i] = A[i-1] + 1, for i >= 1.
 * 
 * For example, for N=18, the shortest possible sequence is:
 *  A[0] = 1
 *  A[1] = 2
 *  A[2] = 4
 *  A[3] = 8
 *  A[4] = 9
 *  A[5] = 18
 * 
 * Write a function:
 *      function solution(N);
 * that, given a positive integer N, returns the length of the shortest possible sequence of integers
 * satisfying the above conditions and ending with N.
 * 
 * For example, given N = 18, the function should return 6, as explained above.
 * 
 * @param {integer} N 
 */

function solution(N) {
    let count = 1;
    for (let i = N; i != 1; ) {
        if (i % 2 == 1) {
            i--;
            count++;
        }
        i /= 2;
        count++;
    }
    return count;
}